#!/system/bin/sh
# call boost scripts if they exist

if [ -e /system/bin/boost.sh ];
then
   log -p i -t boost "Executing /system/bin/boost.sh";
   logwrapper /system/bin/sh /system/bin/boost.sh;
fi;
