# Makefile for busybox
#
# Copyright (C) 1999-2005 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

CFLAGS += -I ./

lib-y:=
lib-$(CONFIG_UDISK_UPGRADE)          += display_interface.o udisk_upgrade_main.o fbutils.o \
					font_8x16.o  font_8x8.o
