#!/system/bin/sh
#

echo "2" > /proc/sys/vm/drop_caches
echo "20" > /proc/sys/vm/swappiness
echo "20" > /proc/sys/vm/dirty_ratio
echo "60" > /proc/sys/vm/vfs_cache_pressure
echo "3000" > /proc/sys/vm/dirty_expire_centisecs
echo "500" > /proc/sys/vm/dirty_writeback_centisecs
echo "5" > /proc/sys/vm/dirty_background_ratio

echo "2048,4096,51200,56320,61440,70400" > /sys/module/lowmemorykiller/parameters/minfree

echo "done Virtual Memory Parameter Tweaks"
