#!/system/bin/sh

mount -o remount,ro,noauto_da_alloc,noatime,nodiratime,barrier=0 /system /system
mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0 /data /data
mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0 /cache /cache